# Generated by Django 4.1.1 on 2022-09-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_address_coupon_order_product_refund_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
