# Generated by Django 4.1.1 on 2022-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_image_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_authenticated",
            field=models.BooleanField(default=False),
        ),
    ]
